// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.Acceptance.Test.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class BCA4ViewListProjectAgencyFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "BCA4ViewListProjectAgency.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BCA4ViewListProjectAgency", "\tAllow Agency see All project about Agency Post", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "BCA4ViewListProjectAgency")))
            {
                global::PPCRental.Acceptance.Test.Feature.BCA4ViewListProjectAgencyFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Content",
                        "Status_Name",
                        "UserID"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table1.AddRow(new string[] {
                        "PIS Top Apartment",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table1.AddRow(new string[] {
                        "Bigroom with Riverview",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table1.AddRow(new string[] {
                        "Phú Mỹ Hưng Quận 7",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table1.AddRow(new string[] {
                        "Scala Quận 9",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 25",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
#line 5
testRunner.Given("All project posted of Agency", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Agency see all project posted")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "BCA4ViewListProjectAgency")]
        public virtual void AgencySeeAllProjectPosted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Agency see all project posted", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 16
 testRunner.Given("Agency have a HomePage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.When("Agency go to Login with username \'shuu27897@gmail.com\' and pass \'tiegviet\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Content",
                        "Status_Name",
                        "UserID"});
            table2.AddRow(new string[] {
                        "Căn hộ Enterprise City",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table2.AddRow(new string[] {
                        "Bigroom with Riverview",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table2.AddRow(new string[] {
                        "Phú Mỹ Hưng Quận 7",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table2.AddRow(new string[] {
                        "Scala Quận 9",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
            table2.AddRow(new string[] {
                        "Căn hộ Enterprise City 25",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6"});
#line 18
 testRunner.Then("All project of Agency show screen", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
