// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.Acceptance.Test.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class BCA5EditOfSaleFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "BCA5EditOfSale.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BCA5EditOfSale", "\tAllow Sales Edit Project", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "BCA5EditOfSale")))
            {
                global::PPCRental.Acceptance.Test.Feature.BCA5EditOfSaleFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
 #line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Content",
                        "Status_Name",
                        "UserID",
                        "Duong",
                        "Phuong",
                        "Quan",
                        "Loạiduan",
                        "TienTe",
                        "Gia",
                        "Dientich",
                        "Phongngu",
                        "Phongtam"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Q.8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
            table1.AddRow(new string[] {
                        "PIS Top Apartment",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Q.8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
            table1.AddRow(new string[] {
                        "Bigroom with Riverview",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Q.8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
            table1.AddRow(new string[] {
                        "Phú Mỹ Hưng Quận 7",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Q.8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
            table1.AddRow(new string[] {
                        "Scala Quận 9",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Q.8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 25",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Q.8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
#line 4
 testRunner.Given("Data of Projects", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Sale can Edit Project anyone Agency")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "BCA5EditOfSale")]
        public virtual void SaleCanEditProjectAnyoneAgency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sale can Edit Project anyone Agency", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 15
 testRunner.Given("Sale at a HomePage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.When("Sale login with account is user:\'root\' and pass:\'toor\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.And("Sales Edit Project \'Căn hộ Enterprise City\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Content",
                        "Status_Name",
                        "UserID",
                        "Duong",
                        "Phuong",
                        "Quan",
                        "Loại du an",
                        "Tien Te",
                        "Gia",
                        "Dien tich",
                        "Phong ngu",
                        "Phong tam"});
            table2.AddRow(new string[] {
                        "JudasFate Căn hộ Enterprise City",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "Đã duyệt",
                        "6",
                        "Cao Lỗ",
                        "P.4",
                        "Quận 8",
                        "House",
                        "USD",
                        "10000",
                        "1000m2",
                        "2",
                        "3"});
#line 18
 testRunner.Then("Result screen project", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
