// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.Appceptance.Test.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class US01_FilterProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "US01_FilterProject.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "US01_FilterProject", "\tAs a potential customer\r\n\tI want to search for property by a simple phrase\r\n\tSo " +
                    "that I can easily allocate property by something I remember from them.", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "US01_FilterProject")))
            {
                global::PPCRental.Appceptance.Test.Feature.US01_FilterProjectFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 10
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "PropertyType",
                        "Street",
                        "Ward",
                        "District"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City",
                        "Apartment",
                        "Đường số 6",
                        "P.13",
                        "Quận 1"});
            table1.AddRow(new string[] {
                        "Topaz Elite mở Bán Block Cuối Cùng Đẹp NhấtDự Án \"dragon 1\"",
                        "Apartment",
                        "Cao lỗ",
                        "P.7",
                        "Quận 8"});
            table1.AddRow(new string[] {
                        "Nhà Phố 3 tầng cao cấp gần khu trung tâm quận 10 và quận 1và quận 5",
                        "House",
                        "Cao lỗ",
                        "P.4",
                        "Quận 8"});
            table1.AddRow(new string[] {
                        "Căn hộ The Gold View",
                        "Apartment",
                        "Bền Vân Đồn",
                        "P.01",
                        "Quận 7"});
            table1.AddRow(new string[] {
                        "Biệt thự lô góc cực đẹp",
                        "Villa",
                        "Huỳnh Tấn Phát",
                        "P.Phú Mỹ",
                        "Quận 7"});
            table1.AddRow(new string[] {
                        "BÁN CĂN HỘ 01 PHÒNG NGỦ Ở VINHOMES CENTRAL PARK",
                        "Apartment",
                        "Điện Biên Phủ",
                        "P.22",
                        "Quận Bình Thạnh"});
            table1.AddRow(new string[] {
                        "Biệt thự Saroma Sala Đại Quang Minh",
                        "Villa",
                        "Xa Lộ Hà Nội",
                        "P.08",
                        "Quận 2"});
            table1.AddRow(new string[] {
                        "Shophouse nhà phố Sala",
                        "House",
                        "Xa Lộ Hà Nội",
                        "P.08",
                        "Quận 2"});
            table1.AddRow(new string[] {
                        "Shop Apartment Sala 1 trệt 2 lầu",
                        "House",
                        "Xa Lộ Hà Nội",
                        "P.08",
                        "Quận 2"});
            table1.AddRow(new string[] {
                        "Căn hộ Sarimi phòng ngủ full nội thất",
                        "Apartment",
                        "Xa Lộ Hà Nội",
                        "P.08",
                        "Quận 2"});
            table1.AddRow(new string[] {
                        "Căn hộ Phú Mỹ Hưng",
                        "Apartment",
                        "Đường Số 14",
                        "P.Phú Mỹ",
                        "Quận 7"});
            table1.AddRow(new string[] {
                        "ĐÔNG NAM DỰ ÁN BOTANICA PREMIER",
                        "Office",
                        "Hồng Hà",
                        "P.2",
                        "Quận Tân Bình"});
            table1.AddRow(new string[] {
                        "CĂN HỘ ĐƯỜNG CỘNG HÒA",
                        "Apartment",
                        "Cộng Hòa",
                        "P.2",
                        "Quận Tân Bình"});
            table1.AddRow(new string[] {
                        "CĂN HỘ PENTHOUSE DUPLEX BẢY HIỀN TOWER",
                        "House",
                        "Cộng Hòa",
                        "P.11",
                        "Quận Tân Bình"});
            table1.AddRow(new string[] {
                        "CĂN HỘ MADISON QUẬN 1",
                        "Office",
                        "Phùng Khắc Khoan",
                        "P.08",
                        "Quận 1"});
            table1.AddRow(new string[] {
                        "VINHOMES ĐỒNG KHỞI",
                        "Apartment",
                        "Lê Thánh Tôn",
                        "P.Bến Nghé",
                        "Quận 1"});
            table1.AddRow(new string[] {
                        "BIỆT THỰ VINHOMES CENTRAL PARK",
                        "Villa",
                        "Điện Biên Phủ",
                        "P.22",
                        "Quận Bình Thạnh"});
            table1.AddRow(new string[] {
                        "CĂN HỘ DRAGON RIVERSIDE CITY QUẬN 5",
                        "Apartment",
                        "Võ Văn Kiệt",
                        "P.01",
                        "Quận 5"});
            table1.AddRow(new string[] {
                        "HÀ ĐÔ CENTROSA GARDEN QUẬN 10",
                        "Office",
                        "3 Tháng 2",
                        "Xuân Thới Sơn",
                        "Quận 10"});
#line 11
 testRunner.Given("the following property", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Title should be matched")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "US01_FilterProject")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void TitleShouldBeMatched()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Title should be matched", new string[] {
                        "mytag"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 10
this.FeatureBackground();
#line 36
 testRunner.Given("I search for property by the phrase \'Enterprise\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.When("I press \"Tim kiem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then("the list of found property should contain only: \'Căn hộ Enterprise City \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
