// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.Appceptance.Test.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ViewListProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "US02_ViewListProject.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ViewListProject", "\tThe agency would like to see its list of projects in the site", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ViewListProject")))
            {
                global::PPCRental.Appceptance.Test.Feature.ViewListProjectFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name Project",
                        "Avatar",
                        "Price",
                        "Area",
                        "Date create",
                        "Note",
                        "Date Update",
                        "Email",
                        "Status"});
            table1.AddRow(new string[] {
                        "Căn hộ The Gold View",
                        "Avatar",
                        "200000",
                        "70",
                        "",
                        "Done",
                        "",
                        "anhphuong123@gmail.com",
                        "Đã duyệt"});
            table1.AddRow(new string[] {
                        "ĐÔNG NAM DỰ ÁN BOTANICA PREMIER",
                        "Avatar",
                        "200000",
                        "92",
                        "",
                        "Done",
                        "",
                        "anhphuong123@gmail.com",
                        "Đã duyệt"});
            table1.AddRow(new string[] {
                        "CĂN HỘ PENTHOUSE DUPLEX BẢY HIỀN TOWER",
                        "Avatar",
                        "280000",
                        "170",
                        "",
                        "Done",
                        "",
                        "anhphuong123@gmail.com",
                        "Đã duyệt"});
#line 5
 testRunner.Given("the following project", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Agency see list project of Agency")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ViewListProject")]
        public virtual void AgencySeeListProjectOfAgency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Agency see list project of Agency", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 13
 testRunner.Given("Agency at the login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.When("Agency login with \'anhphuong123@gmail.com\' and \'123456789\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name Project",
                        "Avatar",
                        "Price",
                        "Area",
                        "Date create",
                        "Note",
                        "Date Update",
                        "Email",
                        "Status"});
            table2.AddRow(new string[] {
                        "Căn hộ The Gold View",
                        "Avatar",
                        "200000",
                        "70",
                        "",
                        "Done",
                        "",
                        "anhphuong123@gmail.com",
                        "Đã duyệt"});
            table2.AddRow(new string[] {
                        "ĐÔNG NAM DỰ ÁN BOTANICA PREMIER",
                        "Avatar",
                        "200000",
                        "92",
                        "",
                        "Done",
                        "",
                        "anhphuong123@gmail.com",
                        "Đã duyệt"});
            table2.AddRow(new string[] {
                        "CĂN HỘ PENTHOUSE DUPLEX BẢY HIỀN TOWER",
                        "Avatar",
                        "280000",
                        "170",
                        "",
                        "Done",
                        "",
                        "anhphuong123@gmail.com",
                        "Đã duyệt"});
#line 15
 testRunner.Then("Agency should see his own project list", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
