// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.Appceptance.Test.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ViewDetailProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "ViewDetailProject.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ViewDetailProject", "\tAllow User see Detail of project", ProgrammingLanguage.CSharp, new string[] {
                        "automated"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ViewDetailProject")))
            {
                global::PPCRental.Appceptance.Test.Feature.ViewDetailProjectFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 10
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Content",
                        "Street_ID",
                        "Ward_ID",
                        "Dictrict_ID",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BebRoom",
                        "BathRoom",
                        "PackingPlace",
                        "UserID"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 22",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 23",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 24",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 25",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "Căn hộ Enterprise City 25",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
#line 11
 testRunner.Given("I have home page of Projejct", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("User see Detail of Project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ViewDetailProject")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("automated")]
        public virtual void UserSeeDetailOfProject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User see Detail of Project", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 10
this.FeatureBackground();
#line 23
 testRunner.When("User click \'Id Project\' one any of project", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Content",
                        "Street_ID",
                        "Ward_ID",
                        "Dictrict_ID",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BebRoom",
                        "BathRoom",
                        "PackingPlace",
                        "UserID"});
            table2.AddRow(new string[] {
                        "17",
                        "Căn hộ Enterprise City",
                        "Sunrise01.JPG",
                        "Sunrise02.JPG",
                        "Nhà đẹp khu dân cư yên tĩnh, có nhiều tiện ích, gần trung tâm quận 7, gần các tru" +
                            "ng tâm thương mại khu vui chơi giải trí như Vivo City, Crescent Mall, Lotte Mart" +
                            ".",
                        "3387",
                        "761",
                        "36",
                        "200000",
                        "USD",
                        "99",
                        "2",
                        "2",
                        "1",
                        "1"});
#line 24
 testRunner.Then("Show Detail Project", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
